# Generated by Django 4.0.1 on 2022-01-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zipecode',
            new_name='zipcode',
        ),
    ]
